[toolchain]
# Stable
#channel   = "1.70.0" # rustc 1.70.0 (84c898d65 2023-05-13)
# Nightly
channel    = "nightly-2023-10-16" # rustc 1.75.0-nightly (42b1224e9 2023-10-15)
components = ["cargo", "clippy", "rustc", "rustfmt", "rust-src"]
profile    = "minimal"
targets    = ["wasm32-unknown-unknown"]
